import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Card } from "primereact/card";
import { SelectButton } from "primereact/selectbutton";
import { useState } from "react";
import InputByCalories from "../components/InputByCalories";
import InputByMacros, { Macros } from "../components/InputByMacros";
import Nav from "../components/Nav";

export default function Home() {
  const [inputType, setInputType] = useState("calories");

  const submitByCalories = (calories: number) => {
    alert("Finding you results for " + calories + " calories per day");
  };

  const submitByMacros = (macros: Macros) => {
    alert(
      "Finding you results for " +
        macros.protein +
        "g protein, " +
        macros.fat +
        "g fat, " +
        macros.carbs +
        "g carbs"
    );
  };

  return (
    <div>
      <Head>
        <title>Open Dietary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Nav></Nav>

        <div className="card m-auto max-w-2xl rounded-lg shadow-lg p-8 mt-12">
          <div className="flex">
            <p>Calculate by:</p>
            <p
              className={`mx-2 clickable-text ${ inputType == "calories" ? "font-semibold" : "" }`}
              onClick={() => setInputType("calories")}
            >
              calories
            </p>
            <p
              className={`clickable-text ${ inputType == "macros" ? "font-semibold" : "" }`}
              onClick={() => setInputType("macros")}
            >
              macros
            </p>
          </div>
          {inputType === "calories" && (
            <InputByCalories
              className="mt-4"
              onSubmit={submitByCalories}
            ></InputByCalories>
          )}
          {inputType === "macros" && (
            <InputByMacros
              className="mt-4"
              onSubmit={submitByMacros}
            ></InputByMacros>
          )}
        </div>
      </div>
    </div>
  );
}
