import Head from "next/head";
import Nav from "../components/Nav";
import { useEffect, useState } from "react";
import { useAuthState } from "react-firebase-hooks/auth";
import Spinner from "../widgets/Spinner";
import { auth } from "../utils/firebase";
import { useRouter } from "next/router";
import { signInWithEmailAndPassword } from "firebase/auth";
import Link from "next/link";

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [user, loading, error] = useAuthState(auth);
  const router = useRouter();

  const signIn = () => {
    if (email == "" || password == "") {
      alert("Please enter your email and password");
    } else if (!loading) {
      signInWithEmailAndPassword(auth, email, password);
    }
  };

  useEffect(() => {
    if (user) {
      const to = router.query.to ?? "";
      router.push("/" + (to as string));
    }
    if (error) {
      alert("Error signing in: " + error.message);
    }
  }, [user, error]);

  return (
    <div>
      <Head>
        <title>Open Dietary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Nav hideLogin={true}></Nav>

        <div className="card m-auto max-w-lg rounded-lg shadow-lg p-8 mt-12">
          <div className="flex justify-center">
            <h2>Welcome back!</h2>
          </div>
          <div className="flex flex-col">
            <div className="mt-4 m-auto">
              <input
                type="text"
                className="text-input-gray"
                value={email}
                placeholder="Email"
                onChange={(e) => setEmail(e.target.value)}
              ></input>
              <br />
              <input
                type="password"
                className="my-2 text-input-gray"
                placeholder="Password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              ></input>
            </div>
            <button className="btn-primary mt-4" onClick={signIn}>
              {loading && <Spinner className="inline mr-2" size={15}></Spinner>}
              Log in
            </button>
            <Link href="/signup">
              <p className="link-text mt-4 text-sm text-center">
                Don't have an account? Create one here.
              </p>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
