import Head from "next/head";
import Nav from "../components/Nav";

export default function MealPlanPage() {
  return (
    <div>
      <Head>
        <title>Open Dietary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Nav></Nav>

        <div className="card m-auto max-w-2xl rounded-lg shadow-lg p-8 mt-12">
            <h1>Meal Plan</h1>
            </div>
      </div>
    </div>
  );
}
