// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCrjxPuzZZ0FmGfD01sOidmC8WZgU2AKg',
    appId: '1:428240700645:web:59d90949ea9b0c8744c00c',
    messagingSenderId: '428240700645',
    projectId: 'opendietary',
    authDomain: 'opendietary.firebaseapp.com',
    databaseURL: 'https://opendietary-default-rtdb.firebaseio.com',
    storageBucket: 'opendietary.appspot.com',
    measurementId: 'G-P9RKK6LZXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlL7HZXL4FCZ9-is75wplJ3d8iEFZSqdQ',
    appId: '1:428240700645:android:d6d19cff9db5634944c00c',
    messagingSenderId: '428240700645',
    projectId: 'opendietary',
    databaseURL: 'https://opendietary-default-rtdb.firebaseio.com',
    storageBucket: 'opendietary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8X6rsY3nMXQWMeGNRr5iw_sEO80WzIT0',
    appId: '1:428240700645:ios:1cc4d25b700dc2e844c00c',
    messagingSenderId: '428240700645',
    projectId: 'opendietary',
    databaseURL: 'https://opendietary-default-rtdb.firebaseio.com',
    storageBucket: 'opendietary.appspot.com',
    iosClientId: '428240700645-b27svj6s142nc1milq251coeiheb4rtt.apps.googleusercontent.com',
    iosBundleId: 'com.opendietary.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8X6rsY3nMXQWMeGNRr5iw_sEO80WzIT0',
    appId: '1:428240700645:ios:1cc4d25b700dc2e844c00c',
    messagingSenderId: '428240700645',
    projectId: 'opendietary',
    databaseURL: 'https://opendietary-default-rtdb.firebaseio.com',
    storageBucket: 'opendietary.appspot.com',
    iosClientId: '428240700645-b27svj6s142nc1milq251coeiheb4rtt.apps.googleusercontent.com',
    iosBundleId: 'com.opendietary.mobile',
  );
}
